### ISSUE TITLE
CHanges proposed - design figures and small figures

### ISSUE THREAD

**Issue by octaviopardo** [octaviopardo/lexend#12]
I m going to list here some of the changes introduced in the font in my last commits. These are not all, but they are the most relevant. I m going to break them in "categories". In this entry I will list the ones regarding design of figures and small figures

IN GREEN PREVIOUS VERSION (LEFT) IN RED NEW VERSION (RIGHT)

<img width="1409" alt="Captura de pantalla 2024-08-22 a las 19 14 34" src="https://github.com/user-attachments/assets/2b3b923f-58b4-4613-a8b5-b9716ef7830d">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 19 14 40" src="https://github.com/user-attachments/assets/d6391303-8088-47fe-ae2b-6b8cdeb4a41d">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 19 14 45" src="https://github.com/user-attachments/assets/2970b4a2-8b38-4ae7-a546-aa7fac747ad3">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 19 14 50" src="https://github.com/user-attachments/assets/f6b11cd7-6b63-4e4c-bc99-c516533ea8f0">

<img width="1409" alt="Captura de pantalla 2024-08-22 a las 11 49 05" src="https://github.com/user-attachments/assets/2623d47f-cb95-43ac-a37f-8065e50ab2a2">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 11 49 15" src="https://github.com/user-attachments/assets/e6a29580-4059-4f6a-be8f-34f55d00661c">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 12 06 51" src="https://github.com/user-attachments/assets/bcd96c6e-242b-4783-b3bd-eba33c207e4f">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 12 22 20" src="https://github.com/user-attachments/assets/f1ad0cae-666d-4c02-841f-1a01dc5094fc">

**Comment by vv-monsalve** [comment]
These changes were reviewed and accepted on September 5th. This issue can be closed here.
