### ISSUE TITLE
Changes proposed - width ordfemenine and ordmasculine

### ISSUE THREAD

**Issue by octaviopardo** [octaviopardo/lexend#4]
I m going to list here some of the changes introduced in the font in my last commits. This are not all, but they are the most relevant. I m going to break them in "categories". In this entry I will list the ones regarding width ordfemenine and ordmasculine symbols. 

IN GREEN PREVIOUS VERSION (LEFT) IN RED NEW VERSION (RIGHT)

<img width="1409" alt="Captura de pantalla 2024-08-22 a las 11 47 43" src="https://github.com/user-attachments/assets/b66b7ceb-8211-438f-92a7-78219ca3f0f9">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 11 47 47" src="https://github.com/user-attachments/assets/88884b1c-b63f-48d0-955d-b6fca558a7f7">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 12 05 43" src="https://github.com/user-attachments/assets/fd60c2b4-56c1-46d4-a790-cc4d7e6e440b">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 12 05 46" src="https://github.com/user-attachments/assets/d2ded44a-9b10-4445-8db2-57c9bd327656">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 12 21 08" src="https://github.com/user-attachments/assets/d736cb42-887c-402e-b566-3cb7acc6dd38">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 12 21 11" src="https://github.com/user-attachments/assets/4d5cef0c-38d1-4160-9963-9ed5f98efb58">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 19 14 21" src="https://github.com/user-attachments/assets/1ded0252-5f01-4369-87a0-ef04c704067a">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 19 14 25" src="https://github.com/user-attachments/assets/82847fe5-469e-4d58-8b58-bb3f195e9fdc">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 28 02" src="https://github.com/user-attachments/assets/a0ea61c1-cbc8-46ec-b704-e8f147b12ba3">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 28 06" src="https://github.com/user-attachments/assets/bf0f2867-8450-42f6-9f6e-45addcdf4242">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 37 08" src="https://github.com/user-attachments/assets/c328ede9-0fbb-4e40-963d-a7d3d68fb85a">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 37 11" src="https://github.com/user-attachments/assets/59349544-1031-4487-9ccf-b3fe60c2258b">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 44 10" src="https://github.com/user-attachments/assets/f9fd3caf-1a5c-4927-92f2-100ea691dfde">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 44 13" src="https://github.com/user-attachments/assets/740cdda6-0df1-4de8-8811-e060cf236a0f">

**Comment by vv-monsalve** [comment]
These changes were reviewed and accepted on September 5th. This issue can be closed here.
