### ISSUE TITLE
Changes proposed - width small figures

### ISSUE THREAD

**Issue by octaviopardo** [octaviopardo/lexend#5]
I m going to list here some of the changes introduced in the font in my last commits. This are not all, but they are the most relevant. I m going to break them in "categories". In this entry I will list the ones regarding width in small figures. In this case fractions are also affected. 

IN GREEN PREVIOUS VERSION (LEFT) IN RED NEW VERSION (RIGHT)

<img width="1409" alt="Captura de pantalla 2024-08-22 a las 11 48 58" src="https://github.com/user-attachments/assets/a3ae0feb-6863-4c8e-85b6-7eb11e6316eb">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 11 49 11" src="https://github.com/user-attachments/assets/d5a69438-4056-47ce-ae38-0c8f8320bfba">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 12 06 40" src="https://github.com/user-attachments/assets/c8faa234-cdc7-4787-a9ac-f4914133967e">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 12 06 45" src="https://github.com/user-attachments/assets/2f583f96-f93b-40de-af2c-4c2b2c0a5371">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 12 06 56" src="https://github.com/user-attachments/assets/5817b790-9724-4092-8387-2ca76a9e8d7a">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 12 22 06" src="https://github.com/user-attachments/assets/fb2ad0fd-d4f9-4aaf-b969-ef65dccb113a">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 12 22 10" src="https://github.com/user-attachments/assets/7016d447-b9c3-4e0e-8e07-121b221c120b">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 12 22 13" src="https://github.com/user-attachments/assets/3d179fbd-075b-4f47-90b2-3229b49ce785">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 12 22 16" src="https://github.com/user-attachments/assets/b19d8338-279a-4054-a940-0e61dd95b559">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 12 22 25" src="https://github.com/user-attachments/assets/732567b5-6adc-4c4e-a8ec-0bce55278e6b">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 19 15 24" src="https://github.com/user-attachments/assets/d61be9ef-4fe3-461f-9e0c-a9a90c4cf4e0">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 19 15 35" src="https://github.com/user-attachments/assets/a786136f-5da2-476c-baa4-6f6d97fcddf1">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 28 52" src="https://github.com/user-attachments/assets/26b7a4e6-1043-4687-b3f1-f984e565378c">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 28 56" src="https://github.com/user-attachments/assets/cb6a7da6-303c-4e61-8136-e7c8b29c27eb">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 28 59" src="https://github.com/user-attachments/assets/03ac929c-ec70-48cb-a0fb-e31efbbc1853">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 29 04" src="https://github.com/user-attachments/assets/856c0120-e851-4a6d-b2c8-2d4147fa4cd7">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 29 06" src="https://github.com/user-attachments/assets/4b385cfa-d580-41ad-ad82-9fb81b51688b">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 29 09" src="https://github.com/user-attachments/assets/8b176de9-f337-4d81-9d36-839d2d24beba">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 29 11" src="https://github.com/user-attachments/assets/7b7e2341-801c-4704-ab88-030b760bdc13">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 29 13" src="https://github.com/user-attachments/assets/d60c777e-e6d9-47bf-9101-66ff2f2a533b">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 29 16" src="https://github.com/user-attachments/assets/20977762-b340-4793-8fb6-88eff597d90f">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 29 18" src="https://github.com/user-attachments/assets/f386b6cf-c028-4d40-acf7-66a733afacd2">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 38 02" src="https://github.com/user-attachments/assets/cb78877d-68c0-420f-af83-a693ddf8482f">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 38 06" src="https://github.com/user-attachments/assets/51b5a056-8270-46cb-8aee-2c0507115572">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 38 12" src="https://github.com/user-attachments/assets/9fa4a1cc-614b-4801-aa92-9d8176f49a64">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 38 14" src="https://github.com/user-attachments/assets/52955c53-1239-4a10-b33e-ff9f3d369bbe">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 38 17" src="https://github.com/user-attachments/assets/5ff37014-348d-4a68-bb96-9eaee1f1a7b8">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 38 19" src="https://github.com/user-attachments/assets/1dfc3d72-ee18-44b3-8aec-e03407ff1959">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 38 21" src="https://github.com/user-attachments/assets/bf03f6f1-d90e-44fe-bc17-58ec3530cbf4">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 38 24" src="https://github.com/user-attachments/assets/c5a38560-c934-43ed-bf85-2b7f49d071cc">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 38 25" src="https://github.com/user-attachments/assets/18ba405f-11e0-49c9-88b3-0f0f5e0be516">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 44 59" src="https://github.com/user-attachments/assets/92cad1dd-9def-4a3b-b378-6e1b27dcca56">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 45 10" src="https://github.com/user-attachments/assets/45fb17ec-4e87-4804-aaca-e72ff76ad404">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 45 13" src="https://github.com/user-attachments/assets/a726097f-31b0-45b4-ad95-83938543b7d1">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 45 18" src="https://github.com/user-attachments/assets/fb8c65d7-44b4-43f0-8cdc-670fb33e46e0">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 45 21" src="https://github.com/user-attachments/assets/e86ca863-b4e9-46b8-97ad-dbaa0683ff31">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 45 24" src="https://github.com/user-attachments/assets/cd9079ff-a5e7-48d8-a4d9-849ea7872147">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 45 27" src="https://github.com/user-attachments/assets/15636643-1e02-4d48-8f0c-c264dc0f0721">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 45 29" src="https://github.com/user-attachments/assets/57444b33-c019-4748-92ef-7bb00b9bdfa3">

**Comment by vv-monsalve** [comment]
These changes were reviewed and accepted on September 5th. This issue can be closed here.
