### ISSUE TITLE
Changes proposed - width symbols

### ISSUE THREAD

**Issue by octaviopardo** [octaviopardo/lexend#6]
I m going to list here some of the changes introduced in the font in my last commits. These are not all, but they are the most relevant. I m going to break them in "categories". In this entry I will list the ones regarding width in different symbols. 

IN GREEN PREVIOUS VERSION (LEFT) IN RED NEW VERSION (RIGHT)

<img width="1409" alt="Captura de pantalla 2024-08-22 a las 11 51 59" src="https://github.com/user-attachments/assets/25b276c3-fa3d-45c4-9d06-807ecc4096f1">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 12 21 20" src="https://github.com/user-attachments/assets/a1116bef-bf13-437c-9938-558b942166fd">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 12 25 03" src="https://github.com/user-attachments/assets/b41bf612-8d7b-4d8c-9b44-e10e4bef5202">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 12 25 28" src="https://github.com/user-attachments/assets/8fab5d0c-dfb0-456f-a363-1bdcc76806aa">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 12 26 03" src="https://github.com/user-attachments/assets/62503679-7707-48aa-b8dc-a61dcbd98df1">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 19 16 09" src="https://github.com/user-attachments/assets/c37a4bfc-33b7-491f-8174-d623b29bc4a7">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 19 17 16" src="https://github.com/user-attachments/assets/778424e5-12f5-45a3-8fbc-52f5752c761f">

**Comment by vv-monsalve** [comment]
All the changes to auxiliary glyphs were reviewed and accepted on September 5th. This issue can be closed here.
