### ISSUE TITLE
Changes Proposed - Accents

### ISSUE THREAD

**Issue by octaviopardo** [octaviopardo/lexend#7]
I m going to list here some of the changes introduced in the font in my last commits. These are not all, but they are the most relevant. I m going to break them in "categories". In this entry I will list the ones regarding width in accents. 

IN GREEN PREVIOUS VERSION (LEFT) IN RED NEW VERSION (RIGHT)

<img width="1409" alt="Captura de pantalla 2024-08-22 a las 11 54 39" src="https://github.com/user-attachments/assets/8e02b323-06e9-4bf0-ba57-1f93c7444390">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 12 00 38" src="https://github.com/user-attachments/assets/ef9bf9ca-ed10-47d9-8bd5-47d335ddf9e3">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 12 03 11" src="https://github.com/user-attachments/assets/7d0fede9-cafe-4cb0-8557-8c670e19f5e5">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 12 03 54" src="https://github.com/user-attachments/assets/83435268-7bdd-4289-b7e5-1e28d218fd31">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 12 17 21" src="https://github.com/user-attachments/assets/53e601d2-e0bd-4fd1-b73f-8bad17f9bda4">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 24 43" src="https://github.com/user-attachments/assets/c6ba1ab4-1518-4f4f-829c-60597e683ae1">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 35 14" src="https://github.com/user-attachments/assets/2def0c81-10d9-41e6-ba5b-cfe8a0e76432">
<img width="1409" alt="Captura de pantalla 2024-08-23 a las 11 36 08" src="https://github.com/user-attachments/assets/99d429d4-a3d6-4c09-9d64-ebe3f5272410">

**Comment by vv-monsalve** [comment]
These changes were reviewed and accepted on September 5th. This issue can be closed here.
