### ISSUE TITLE
Changes Proposed - Ogoneks

### ISSUE THREAD

**Issue by octaviopardo** [octaviopardo/lexend#8]
I m going to list here some of the changes introduced in the font in my last commits. These are not all, but they are the most relevant. I m going to break them in "categories". In this entry I will list the ones regarding ogneks. 

IN GREEN PREVIOUS VERSION (LEFT) IN RED NEW VERSION (RIGHT)

<img width="1409" alt="Captura de pantalla 2024-08-22 a las 11 36 56" src="https://github.com/user-attachments/assets/96b24d31-ad21-41ee-a061-f68e67bf94f4">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 11 37 51" src="https://github.com/user-attachments/assets/5c21b594-04e2-4dc5-a3e0-b2314450b52d">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 11 42 28" src="https://github.com/user-attachments/assets/2009eba5-4624-4096-9ce9-6b857108a44f">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 12 02 32" src="https://github.com/user-attachments/assets/3803d61c-9034-436d-8741-2ea5f63e89a4">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 19 04 25" src="https://github.com/user-attachments/assets/45deaf6e-74bf-4761-852e-1c57d371e7fa">

**Comment by vv-monsalve** [comment]
These changes were reviewed and accepted on September 5th. This issue can be closed here.
