### ISSUE TITLE
Changes Proposed - Eth/Dcroat, Hbar Lslash…

### ISSUE THREAD

**Issue by octaviopardo** [octaviopardo/lexend#9]
I m going to list here some of the changes introduced in the font in my last commits. These are not all, but they are the most relevant. I m going to break them in "categories". In this entry I will list the ones regarding design in some accented letters 

IN GREEN PREVIOUS VERSION (LEFT) IN RED NEW VERSION (RIGHT)

<img width="1409" alt="Captura de pantalla 2024-08-22 a las 11 35 52" src="https://github.com/user-attachments/assets/35c0e5c0-a660-4c75-adb1-f6b325e4e5cd">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 11 55 53" src="https://github.com/user-attachments/assets/64cdeca7-b571-4e22-bd42-5d185c6e10eb">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 12 12 45" src="https://github.com/user-attachments/assets/11113d88-69f7-45ad-9944-b3dc461ff38b">

<img width="1409" alt="Captura de pantalla 2024-08-22 a las 11 37 18" src="https://github.com/user-attachments/assets/fe77d780-6873-454e-a1bc-340e886726e1">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 11 43 02" src="https://github.com/user-attachments/assets/8953a218-11f8-44db-94a6-b5a2788f355f">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 11 57 01" src="https://github.com/user-attachments/assets/edf87e19-0fdd-4e00-b01c-3c06f9841df9">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 12 13 41" src="https://github.com/user-attachments/assets/4374798a-382d-465a-871c-beee59371560">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 12 15 02" src="https://github.com/user-attachments/assets/772e5c7f-3d65-40d6-a184-afc5969d05d4">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 12 18 05" src="https://github.com/user-attachments/assets/f74e33c0-c240-41c7-9657-a7602842d7aa">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 19 06 27" src="https://github.com/user-attachments/assets/a6dadd64-cae9-463a-a512-c7151e63aa2a">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 19 11 47" src="https://github.com/user-attachments/assets/509d9706-40b5-45c7-bd15-d657c183cb61">
<img width="1409" alt="Captura de pantalla 2024-08-22 a las 19 12 18" src="https://github.com/user-attachments/assets/2ca8e8bc-1621-447e-adf5-f7474763c758">

**Comment by vv-monsalve** [comment]
These changes were reviewed and accepted on September 5th. This issue can be closed here.
